#!/bin/bash

# ステージされた .swift ファイルを対象にする
FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.swift$')

for file in $FILES; do
  # 行末スペース削除 + 空白のみの行を空行に変換
  perl -i -lpe 's/\s+$//' "$file"

  # 再ステージ
  git add "$file"
done
